apiVersion: v1
kind: Service
metadata:
  name: api-products
  annotations:
    networking.gke.io/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: api-products
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
